# Requisição POST para criar um novo usuário
POST http://localhost:3000/users
Content-Type: application/json

{
  "name":"icaro botelho",
  "email":"icaro@example.com",
  "password":"12345"
}

###

# Requisição GET para listar todos os usuários
GET http://localhost:3000/users

---